# Change these first
owner: AltiVR # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Altific's Humble Abode (AHA)
    url: https://www.altific.net/
  - name: Altific Soundish
    url: https://www.altific.net/account/soundish

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.altific.net
  # baseUrl: /your-repo-name
  logoUrl: https://drive.google.com/file/d/1nLu4U7mxFFR34-KFsAzSLYok5Z-ddLNH/preview
  name: AltiStatus
  navbar:
    - title: Status
      href: /
    - title: Altific's Humble Abode
      href: https://www.altific.net/
